# Generated by Django 5.1.1 on 2024-10-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5)),
                ('guess_history', models.CharField(blank=True, max_length=30)),
                ('guesses', models.PositiveSmallIntegerField(default=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('solved', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wordle',
                'verbose_name_plural': 'Wordles',
                'db_table': 'wordle',
            },
        ),
    ]
