# Generated by Django 5.1.1 on 2024-10-20 23:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('users', '0001_initial'),
        ('token_blacklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, default='Unknown Location', max_length=255)),
                ('device', models.CharField(blank=True, default='Unknown Device', max_length=255)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='token_blacklist.outstandingtoken')),
            ],
        ),
    ]
